export default {
  LOADING: 'loading',
  UPDATE_INTERNET_FIELDS: 'update internet field',
  HOME_REDUCER: 'home reducer',
  AUTH_REDUCER: 'auth reducer',
  UPDATE_UUID: 'update uuid',
  CATEGORY_INFO: 'category info',
  PRODUCTLIST_INFO: 'productlist info',
  FILTER_INFO: 'filter info',
  ACTIVE_FILTERS: 'active filters',
  USER_LOGOUT: 'user logout',
  PRODUCTS_COUNT: 'products count',
  BASKET_INFO: 'basket',
  DO_LOAD_MORE: 'load_more',
  PDP_DETAIL: 'PDP detail',
  SEARCH_SUGGESTIONS: 'search suggestions',
  PRODUCT_SEARCH_RESULTS: 'product search results',
  PRODUCT_SEARCH_RESULTS_COUNT: 'product search results count',
  ACTIVE_SEARCH_FILTERS: 'active search filters',
  USER_REDUCER: 'USER_REDUCER',
  PROFILE_REDUCER: 'PROFILE_REDUCER',
  SESSION: 'session',
  TRACK_STATE: 'track_state',
  TRACK_ACTION: 'track_action',
  RISKIFIED_TOKEN: 'riskified_token',
  PUSH_AUTH: 'push_auth',
  STATIC_DATA: 'Static Content',
  MISC_INFO: 'miscellaneous info',
  QUANTITY: 'quantity',
  REMOVE_FROM_CART: 'remove from cart',
  SHOW_UNDO: 'show undo',
  PROMOTIONS: 'promotions',
  SIGNUP_INFO: 'signup info',
  RECENTLY_VIEWED: 'recently viewed',
  RECENT_SEARCHES: 'recent searches',
  CUSTOMISATION_STATE: 'customisation State',
  RESET_CUSTOMISATION_STATE: 'customisation Reset',
  UPDATE_IMAGE: 'Update custom object image',
  UPDATE_IMAGE_ROTATION: 'Update custom object image rotation',
  UPDATE_IMAGE_SCALE: 'Update custom object image scale',
  UPDATE_PRODUCT_TYPE: 'Update product Type',
  DIGITAL_CARD_STATE: 'Digital Card State',
  POD_CARD_STATE: 'POD Card State',
  UPDATE_SENDER_ADDRESS: 'Update Sender Address',
  UPDATE_RECIPIENT_ADDRESS: 'Update Recipient Address',
  POD_DELIVERY_OPTIONS: 'Update POD Delivery Options',
  DIGITAL_DELIVERY_OPTIONS: 'Update Digital Delivery Options',
  UPDATE_RECIPIENT_EMAIL_ADDRESS: 'Update Recipient Email Address',
  UPDATE_TEXT_DELIVERY: 'Update Delivery as Text',
  DELETE_IMAGE: 'Image deleted',
  ADD_TEXT: 'Add text',
  DELETE_INSIDE_TEXT: 'Delete Inside Text',
  UPDATE_INSIDE_TEXT: 'Update Inside Text',
  PREVIEW_TEMPLATE: 'Preview template',
  DISCARD_TEXT_EDITING: 'Discard Text Editing',
  UPDATE_PAN: 'Update pan coordinates',
  UPDATE_TEXT_POSITION: 'Update Text Position',
  ADD_SLIDER_INDEXES: 'Add Slider Indexes',
  SET_HEIGHT_WIDTH_TEXTBOX: 'Set Height Width Textbox',
  FIT_LOCAL_TEXT_TO_FABRIC_OBJ: 'Fit local text to fabric object',
  SAVE_PERSONALIZATION: 'Save personalization',
  SHOW_MESSAGE: 'ShowMessage',
  CUSTOMIZATION_INITIAL_STATE: 'initial customization object',
  PAYMENT_METHODS_REDUCER: 'PAYMENT_METHODS_REDUCER',
  CARE_ADD_REASON: 'CARE_ADD_REASON',
  CARE_ADD_INFO: 'CARE_ADD_INFO',
  CARE_ADD_CASE_ID: 'CARE_ADD_CASE_ID',
  CARE_ADD_CASE_NUM: 'CARE_ADD_CASE_NUM',
  CARE_ADD_FILE: 'CARE_ADD_FILE',
  CARE_REMOVE_FILE: 'CARE_REMOVE_FILE',
  CARE_UPDATE_FILE: 'CARE_UPDATE_FILE',
  CARE_UPDATE_FILE_PROGRESS: 'CARE_UPDATE_FILE_PROGRESS',
  CARE_CLEAR_CASE: 'CARE_CLEAR_CASE',
  CARE_FILES_UPDATE_FINISHED: 'CARE_FILES_UPDATE_FINISHED',
  ORDER_HISTORY_SET_LIST: 'ORDER_HISTORY_SET_LIST',
  ORDER_HISTORY_ADD_TO_LIST: 'ORDER_HISTORY_ADD_TO_LIST',
  ORDER_HISTORY_CLEAR_LIST: 'ORDER_HISTORY_CLEAR_LIST',
  UPDATE_IMAGE_CROP: 'Crop Image'
}
