export default {
  home: '/slot-content?id=app-homepage',
  signIn: '/login',
  signUp: '/create-account',
  forgotPass: '/forgot-password',
  editProfile: '/customer/update-profile',
  categories: '/category/categories',
  categories_banner: '/slot-content?id=clp',
  products: '/product/product-search',
  searchProducts: '/product/bloomreach-search',
  product: '/product/products',
  productDetail: '/product/products',
  productSearchSuggestion: '/product/search-suggestion',
  logout: '/customer/logout',
  appConfig: '/app-config',
  session: '/customer/session',
  podDeliveryOption: 'product/pod-delivery-options',
  digitalDeliveryOption: 'product/digital-delivery-options',
  getBasketCart: '/customer/basket',
  addToCart: '/basket/item',
  updateCartItem: '/basket/item/',
  paypalToken: '/payment/token',
  profile: '/customer/profile',
  password: '/customer/password',
  payments: '/customer/payment-methods',
  applyPromo: '/basket/promo',
  createCase: '/care/create-case',
  caseDetails: '/care/get-case-details',
  addCaseFiles: '/care/add-case-record',
  orderHistory: '/order/history',
  orderDetail: '/order/detail',
  makePaymentDefault: '/customer/payment-methods/set-default',

  //Cutomisation API CALLS
  authorize: '/authorize',
  initialize: '/initialize',
  photoTrayImg: '/photo-tray-images'
}
