export default {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  HOME_SCREEN: 'Home Screen',
  HOME_NAVIGATOR: 'Home',
  ACCOUNT_NAVIGATOR: 'Account',
  SHOP_NAVIGATOR: 'Discover',
  CART_NAVIGATOR: 'Cart',
  CART_SCREEN: 'Cart Screen',
  CHECKOUT_MODAL: 'Checkout Modal',
  ACCOUNT_SCREEN: 'AccountOverview',
  ACCOUNT_DELETE_SCREEN: 'AccountDeleteScreen',
  ACCOUNT_DETAILS_SCREEN: 'AccountDetails',
  ACCOUNT_DIGITAL_ORDER_HISTORY: 'AccountDigitalOrderHistory',
  ACCOUNT_ORDERS_SCREEN: 'AccountOrderHistory',
  ACCOUNT_ORDER_DETAILS_SCREEN: 'AccountOrderDetails',
  ACCOUNT_PAYMENTS_SCREEN: 'AccountPayments',
  ACCOUNT_ADD_PAYMENT: 'AccountAddPayment',
  ACCOUNT_CUSTOMER_SERVICE_SCREEN: 'AccountCustomerService',
  ACCOUNT_CUSTOMER_SERVICE_MESSAGE: 'AccountCustomerServiceMessage',
  ACCOUNT_CUSTOMER_SERVICE_INFORMATION: 'AccountCustomerServiceInformation',
  ACCOUNT_CUSTOMER_SERVICE_FILES: 'AccountCustomerServiceFiles',
  ACCOUNT_CHANGE_PASSWORD: 'AccountChangePassword',
  ACCOUNT_EDIT_DETAILS: 'AccountEditDetails',
  SHOP_SCREEN: 'Shop Screen',
  CLP_SCREEN: 'CLP Screen',
  AUTH_NAVIGATOR: 'Auth',
  BOTTOM_TAB: 'Bottom Tab',
  PLP: 'PLP',
  FILTER_MODAl: 'Filter Modal',
  HOME_SEARCH_SCREEN: 'Home Search Screen',
  PDP_SCREEN: 'PDP Screen',
  SEARCH_SCREEN: 'Search Screen',
  SEARCH_RESULT_SCREEN: 'Search Result Screen',
  SEARCH_LIST_RESULT_SCREEN: 'Search List ResultScreeen',
  SEARCH_FILTER_MODAl: 'Search Filter Modal',
  ROOT_AUTH_NAVIGATOR: 'Root Auth',
  SUPPORT_SCREEN: 'SUPPORT_SCREEN',
  ORDER_HISTORY: 'Order History',
  HELP_CENTER_MODAL: 'Help Center Modal',
  CHAT_SCREEN_MODAL: 'Chat Screen Modal',
  PRIVACY_MODAL: 'Privacy Modal',
  TERMS_MODAL: 'Terms Modal',
  STORE_MAP: 'STORE MAP',
  QR_CODE_MODAL: 'Qr Code Modal',
  ORDER_DETAILS_WEBVIEW: 'Order Details WebView',
  PAYMENT_SCREEN: 'Payment Screen',
  GIFT_CARD_SCREEN: 'Gift Card Screen',
  CONTACTUS_SCREEN: 'ContactUs Screen',
  PRODUCT_SAFETY_SCREEN: 'Product Safety Screen',
  EDIT_PROFILE_SCREEN: 'Edit Profile Screen',
  ADD_ADDRESS_SCREEN: 'Add Address Screen',
  CHANGE_PASSWORD_SCREEN: 'Change Password Screen',
  PRIVACY_INQUIRY_SCREEN: 'Privacy Inquiry Screen',
  CONTACTUS_MODAL: 'Contactus Modal',
  ADDRESS_VERIFICATION_SCREEN: 'Address Verification Screen',
  ORDER_CONFIRM_MODAL: 'Order Confirmation Screen',
  ONBOARDING_SCREEN: 'OnBoarding Screen',
  OFFER_SCREEN: 'Offer Screen',
  DELIVERY_METHOD_SCREEN: 'Delivery Method Screen',
  ANIMATION_PREVIEW_SCREEN: 'Animation Preview Screen',
  LOAD_TEMPLATE: 'Load Template',
  PDP_SCREEN_NAVIGATOR: 'PDP main Modal Navigator',
  ALBUM_MODAL: 'Albums List Modal',
  POD_ADDTOCART: 'POD Add To Cart',
  PAYPAL_PAYMENT_SCREEN: 'Paypal Payment Screen',
  PAYPAL_CHECKOUT_SCREEN: 'Paypal Checkout Screen',
  SUCCESS_DIGITAL_SEND: 'Successful Delivery Digital'
}
